### ISSUE TITLE
Switch to java 1.7 to use ThreadLocalRandom?

### ISSUE THREAD

**Issue by rborer** [clj-commons/dirigiste#25]
Hi,

Java 7 introduced [ThreadLocalRandom](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadLocalRandom.html) object that we could use to replace those lines: https://github.com/ztellman/dirigiste/blob/f8d90d81ba324d020ad5bea93e97da9985616491/src/io/aleph/dirigiste/Stats.java#L19-L23

What do you think of such change? I can submit a PR to introduce it if you think it's fine to remove Java 6 compatibility in Dirigiste.

**Comment by ztellman** [comment]
I think we can safely lose Java 6 compatibility. A PR would be welcome.

**Comment by rborer** [comment]
@ztellman I've been running my own fork of dirigiste with #26, #24 and #27 included since a few days and didn't notice any regression (except the bloody OOM within Aleph that I'm still chasing...). Could you consider the inclusion of those 3 PRs for the next dirigiste release? Thanks.

**Comment by rborer** [comment]
@ztellman As you seem to be looking at aleph PRs right now any chance you look into the 3 dirigiste changes above? 😉
