### ISSUE TITLE
awaitTermination should return false if latch triggered

### ISSUE THREAD

**Issue by SevereOverfl0w** [clj-commons/dirigiste#29]
https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ExecutorService.html#awaitTermination(long,%20java.util.concurrent.TimeUnit)

>     true if this executor terminated and false if the timeout elapsed before termination

However, in practice it seems to return true for a trivial case:

```
(let [^io.aleph.dirigiste.Executor executor (manifold.executor/fixed-thread-executor 1)]
  (.executeWithoutRejection executor #(do
                                        (.println System/out "Hello")
                                        (Thread/sleep 10000)
                                        (.println System/out "Bye, everybody")))
  (.shutdown executor)
  (.awaitTermination executor 5 java.util.concurrent.TimeUnit/SECONDS))
```

Maybe it should be `<= 0` instead for the check?

**Comment by arnaudgeiser** [comment]
I got the fix here : https://github.com/clj-commons/dirigiste/commit/150c918b3d249717caa6f479d948a77c8e7cc771

Waiting for this PR being merged before opening a new one: https://github.com/clj-commons/dirigiste/pull/32
