### ISSUE TITLE
Question: Is there a reason why threads are not created as daemon?

### ISSUE THREAD

**Issue by eric** [clj-commons/dirigiste#8]
It seems that dirigiste is causing my java processes to not exit and I noticed that threads are not being started as daemon threads. Is that intentional? Is there something I should do to make my process exit nicely?

**Comment by ztellman** [comment]
You can specify a ThreadFactory, but I agree that daemon threads could be a
better default.

**Comment by eric** [comment]
I've gone that route and it does appear to have fixed the hang I was seeing!

**Comment by arnaudgeiser** [comment]
It has been changed : https://github.com/clj-commons/dirigiste/commit/eac606222ee2976a4b8b94c060d424d5c0b1f37b
